# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 3.1.x
    
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Display dotnet versions
      run: dotnet --list-sdks
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test .NET Core 3.1
      run: dotnet test --no-build --framework netcoreapp3.1 --verbosity normal
    
    - name: Test .NET 8.0
      run: dotnet test --no-build --framework net8.0 --verbosity normal
    
    - name: Package for Nuget
      run: dotnet pack --no-build --configuration Release
    #- name: Publish Nuget to GitHub registry
    #  run: dotnet nuget push ./src/bin/Release/*.nupkg -s https://nuget.pkg.github.com/FlatlinerDOA/index.json -k ${GITHUB_TOKEN}
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
